<!-- Demographics and description of MB11 sample, selection criteria. -->
The sample consists of `r nrow(demography)` individuals from Middenbeemster,
a 19th century rural Dutch site.
The village of Middenbeemster and the surrounding Beemsterpolder was established
in the beginning of the 17th century, when the Beemster lake was drained to
create more farmland, mainly for the cultivation of cole seeds (de Vries 1978).
In 1615, a decision was made to build a church, and
construction started in 1618 (Hakvoort 2013). The excavated cemetery is associated
with the Keyserkerk church, where the inhabitants of the Middenbeemster village
and the surrounding Beemsterpolder were buried between AD 1615 and 1866
[@lemmersMiddenbeemster2013]. Archival documents are available for those buried
between AD 1829 and 1866, when the majority of individuals were interred.
The main occupation of the inhabitants
was dairy farming, consisting largely of manual labour prior to the industrial
revolution [@aten400Jaar2012; @palmerActivityReconstruction2016].

For our sample, we preferentially selected males from the middle adult age category
(35-49 years) to minimise the effect of confounding cultural and biological factors.
Previous research on Middenbeemster has shown a gendered division of labour
[@palmerActivityReconstruction2016], and there are biological differences in
dental calculus formation and drug metabolism that are related to age and sex
[@huangDecipheringGenetic2023; @unoSexAgedependent2017; @whiteDentalCalculus1997].
The sample consists of `r nrow(filter(demography, sex == "m"))` males,
`r nrow(filter(demography, sex == "pm"))` probable males,
`r nrow(filter(demography, sex == "pf"))` probable females, and
`r nrow(filter(demography, sex == "f"))` female (@fig-sample-demography).
We selected males due to a higher
occurrence of pipe notches and dental calculus deposits than females (unpublished observation).

<!-- use plot to show original and replicated sample demographics? -->
```{r}
#| label: fig-sample-demography
#| fig-cap: "Overview of sample demography. Left plot is the first batch and right plot is the replication batch with 29 of the individuals from the first batch. eya = early young adult (18-24 years); lya = late young adult (25-34 years); ma = middle adult (35-49 years); old = old adult (50+ years). Male? = probable male; Female? = probable female."

# create tables for demographics if there are tables to spare in the article
first_batch <- demography %>%
  #left_join(select(metadata, id, replicated)) %>%
  mutate(sex = factor(sex, levels = c("f", "pf", "pm", "m"))) %>% 
  ggplot(aes(x = age, fill = sex)) +
    geom_bar() +
    scale_fill_viridis_d(drop = FALSE, labels = c("Female", "Female?", "Male?", "Male")) +
    theme_minimal() +
    labs(y = "Count", fill = "Sex") +
    theme(
      panel.grid.major.x = element_blank(),
      axis.title.x = element_blank(),
      plot.margin = unit(c(0,0,0.5,0), "cm")
    )

second_batch <- demography %>%
  left_join(select(metadata, id, replicated)) %>%
  filter(replicated == TRUE) %>% 
  mutate(sex = factor(sex, levels = c("f", "pf", "pm", "m"))) %>% 
  ggplot(aes(x = age, fill = sex)) +
    geom_bar() +
    scale_fill_viridis_d(drop = FALSE, labels = c("Female", "Female?", "Male?", "Male")) +
    scale_y_continuous(limits = c(0,25)) +
    theme_minimal() +
    labs(fill = "Sex") +
    theme(
      axis.title = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      panel.grid.major.x = element_blank()
    )

first_batch + second_batch + plot_layout(guides = "collect")

grid::grid.draw(grid::textGrob("Age-at-death", x =.45, y=0.045))
```
