```{r}
#| label: setup
#| include: false
#| cache: false

library(here)
library(readr)
devtools::load_all()

# upload data
metadata <- read_tsv(here("analysis/data/raw_data/metadata.tsv"))
demography <- read_csv(here("analysis/data/raw_data/demography.csv"))
lloq <- read_tsv(here("analysis/data/raw_data/lloq.tsv"))
uhplc_data_comb <- read_csv(here("analysis/data/derived_data/uhplc-data_combined.csv"))
dental_inv <- read_csv(here("analysis/data/raw_data/dental-inv.csv"))
caries <- read_csv(here("analysis/data/raw_data/caries.csv"))
periodont <- read_csv(here("analysis/data/raw_data/periodontitis.csv"))
periap <- read_csv(here("analysis/data/raw_data/periapical.csv"))
#calculus <- read_csv(here("analysis/data/raw_data/calculus.csv"))
calculus_full <- read_csv(here("analysis/data/raw_data/calculus_full.csv"))
sinusitis_clean <- read_csv(here("analysis/data/derived_data/sinusitis_cleaned.csv"))
path_cond_clean <- read_csv(here("analysis/data/derived_data/path-conditions_cleaned.csv"))

source(here("analysis/scripts/setup-qmd.R"))
#source(here("analysis/supplementary-materials/supp-mat.qmd"), local = knitr::knit_global())
# set viridis as default pallette

options(ggplot.discrete.colour = function() scale_fill_viridis_d())
```
 
Keywords: {{< meta keywords >}}

<!-- Highlights: {{< meta highlights >}} -->

## Introduction

{{< include _intro.qmd >}}

## Materials

{{< include _materials.qmd >}}

## Methods

{{< include _methods.qmd >}}

## Results

{{< include _results.qmd >}}

## Discussion

{{< include _discussion.qmd >}}

## Conclusions

{{< include _conclusions.qmd >}}

## Acknowledgements {-}

We wish to thank Kirsten Ziesemer for helping track down the calculus samples
from her studies. Additionally, we owe special thanks to Vincent Falger and Kees
de Groot from the Middenbeemster Historical Society for their input on early
draft manuscripts and a lovely guided tour of Middenbeemster.

This research has received funding from the European Research Council under the
European Union’s Horizon 2020 research and innovation program, grant agreement
number STG–677576 (“HARVEST”).

## Data Availability Statement

All raw data is available on Zenodo (<https://doi.org/10.5281/zenodo.7648757>).
Analysis scripts, and the source code for the manuscript and
supplementary materials are available as a research compendium<!--Zenodo link-->
using the structure recommended by the **rrtools** R package [@Rrrtools].

## References {-}

::: {#refs}
:::
